[workspace]
members=[
"yogamat",
"backend",
]
resolver="2"

[profile.dev.package."*"]
opt-level = 3

[profile.wasm-release]
inherits = "release"
opt-level = "z" 
lto = "fat"
codegen-units = 1


[workspace.dependencies]


