services:
  server:
    build: backend
    ports:
      - 3000:3000
    volumes:
      - www:/app/dist
    environment:
      - APP_APPLICATION__CLIENT_ID
      - APP_APPLICATION__CLIENT_SECRET

  yoga:
    build: frontend
    volumes:
      - www:/frontend/dist
volumes:
  www: 

