[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"

[dependencies]
actix-web = "4.3.0"
base64 = "0.21.0"
dotenv = "0.15.0"
rand = "0.8.5"
secrecy = "0.8.0"
sha2 = "0.10.6"
urlencoding = "2"

