application:
  port: 3000
  oauth_providers:
    -
      name: fusion
      oauth_url: http://aquiles.local:9011/oauth2/authorize
      token_url: http://aquiles.local:9011/oauth2/token
      revoke_url: http://aquiles.local:9011/revoke
    -
      name: google
      oauth_url: https://accounts.google.com/o/oauth2/v2/auth
      token_url: https://oauth2.googleapis.com/token
      revoke_url: https://oauth2.googleapis.com/revoke
    -
      name: github
      oauth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token
      revoke_url: https://github.com/login/oauth/idontknowrevoke
database:
  username: "postgres"
  password: "password"
  port: 5432
  host: "localhost"
  database_name: "newsletter"
  require_ssl: false
