application:
  host: 0.0.0.0
  oauth_redirect_url: https://baeuerlin.net/oauth-redirect
  oauth_url: https://accounts.google.com/o/oauth2/v2/auth
  token_url: https://oauth2.googleapis.com/token
  revoke_url: https://oauth2.googleapis.com/revoke
