application:
  host: 0.0.0.0
  oauth_redirect_url: https://portfolio.baeuerlin.net/api/v1/oauth-redirect
  after_login_url: https://portfolio.baeuerlin.net/login-success
  allowed_origins:
    - https://portfolio.baeuerlin.net
